apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: knmp
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql-app
    spec:
      containers:
        - image: mysql:8.4
          imagePullPolicy: Always
          name: mysql-app
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: root-pass
                  name: mysql-secret-db
            - name: MYSQL_DATABASE
              value: "appdb"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: mysql-secret-db
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-secret-db
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "1"
          resources:
            requests:
              cpu: "0.5"
#          volumeMounts:
#            - mountPath: /var/lib/mysql
#              name: mysql-data
#      volumes:
#        - name: mysql-data
#          persistentVolumeClaim:
#            claimName: mysql-data
