apiVersion: v1
kind: Service
metadata:
  namespace: knmp
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mysql-app
  ports:
    - name: mysql-service-port
      port: 3306
      targetPort: 3306
      protocol: TCP
