apiVersion: v1
kind: Service
metadata:
  namespace: knmp
  name: phpmyadmin-service
spec:
  type: NodePort
  selector:
    app: phpmyadmin-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 80